-- mod-version: 3
-- Bare minimum Lite XL syntax highlighting for Joy

local syntax = require "core.syntax"

syntax.add {
  name = "Joy",
  files = { "%.joy$" },
  block_comment = { "(*", "*)" },
  symbol_non_word_chars = " \t\n'{}",

  patterns = {
    { pattern = { "%(%*", "%*%)" }, type = "comment" },
    { pattern = { '"', '"', '\\' }, type = "string" },

    { pattern = "#[xX]#?[eEiI]?[%-%+]?[%x]+%.?[%x]*",  type = "number" },
    { pattern = "#[oO]#?[eEiI]?[%-%+]?[0-7]+%.?[0-7]*", type = "number" },
    { pattern = "#[bB]#?[eEiI]?[%-%+]?[01]+%.?[01]*",   type = "number" },
    { pattern = "#[eEiI]?#?[dD]?[%-%+]?%d+/%d+",       type = "number" },
    { pattern = "#[eEiI]?#?[dD]?[%-%+]?%d+%.%d+",      type = "number" },
    { pattern = "#[eEiI]?#?[dD]?[%-%+]?%.%d+",         type = "number" },
    { pattern = "#[eEiI]?#?[dD]?[%-%+]?%d+",           type = "number" },
    { pattern = "[%-%+]?%d+/%d+",                      type = "number" },
    { pattern = "[%-%+]?%d+%.%d+",                     type = "number" },
    { pattern = "[%-%+]?%.%d+",                        type = "number" },
    { pattern = "[%-%+]?%d+%.?",                       type = "number" },

    { pattern = "+", type = "operator" },
    { pattern = "-", type = "operator" },
    { pattern = "*", type = "operator" },
    { pattern = "/", type = "operator" },
    { pattern = "%%", type = "operator" },
    { pattern = "=", type = "operator" },
    { pattern = "==", type = "operator" },
    { pattern = "!=", type = "operator" },
    { pattern = "<", type = "operator" },
    { pattern = ">", type = "operator" },
    { pattern = "<=", type = "operator" },
    { pattern = ">=", type = "operator" },
    { pattern = "%.", type = "operator" },
    { pattern = ";", type = "operator" },

    { pattern = "%[", type = "literal" },
    { pattern = "%]", type = "literal" },
    { pattern = "{",  type = "literal" },
    { pattern = "}",  type = "literal" },

    { pattern = "%.?[%a_][%w_%-%?>]*", type = "symbol" },
  },

  symbols = {
    ["dup"] = "keyword",
    ["pop"] = "keyword",
    ["swap"] = "keyword",
    ["dupd"] = "keyword",
    ["popd"] = "keyword",
    ["swapd"] = "keyword",
    ["rollup"] = "keyword",
    ["rolldown"] = "keyword",
    ["rotate"] = "keyword",
    ["rollupd"] = "keyword",
    ["rolldownd"] = "keyword",
    ["rotated"] = "keyword",
    ["id"] = "keyword",
    ["clear"] = "keyword",
    ["stack"] = "keyword",
    ["unstack"] = "keyword",
    [".s"] = "keyword",
    ["div"] = "keyword",
    ["rem"] = "keyword",
    ["neg"] = "keyword",
    ["abs"] = "keyword",
    ["succ"] = "keyword",
    ["pred"] = "keyword",
    ["sign"] = "keyword",
    ["min"] = "keyword",
    ["max"] = "keyword",
    ["sqrt"] = "keyword",
    ["pow"] = "keyword",
    ["band"] = "keyword",
    ["bor"] = "keyword",
    ["bxor"] = "keyword",
    ["bshift"] = "keyword",
    ["sin"] = "keyword",
    ["cos"] = "keyword",
    ["tan"] = "keyword",
    ["asin"] = "keyword",
    ["acos"] = "keyword",
    ["atan"] = "keyword",
    ["atan2"] = "keyword",
    ["sinh"] = "keyword",
    ["cosh"] = "keyword",
    ["tanh"] = "keyword",
    ["log"] = "keyword",
    ["log10"] = "keyword",
    ["exp"] = "keyword",
    ["floor"] = "keyword",
    ["ceil"] = "keyword",
    ["trunc"] = "keyword",
    ["round"] = "keyword",
    ["modf"] = "keyword",
    ["chr"] = "keyword",
    ["ord"] = "keyword",
    ["strtod"] = "keyword",
    ["strtol"] = "keyword",
    ["format"] = "keyword",
    ["formatf"] = "keyword",
    ["equal"] = "keyword",
    ["compare"] = "keyword",
    ["and"] = "keyword",
    ["or"] = "keyword",
    ["not"] = "keyword",
    ["xor"] = "keyword",
    ["cons"] = "keyword",
    ["swons"] = "keyword",
    ["uncons"] = "keyword",
    ["first"] = "keyword",
    ["rest"] = "keyword",
    ["size"] = "keyword",
    ["empty?"] = "keyword",
    ["concat"] = "keyword",
    ["reverse"] = "keyword",
    ["at"] = "keyword",
    ["take"] = "keyword",
    ["drop"] = "keyword",
    ["in"] = "keyword",
    ["has"] = "keyword",
    ["chars"] = "keyword",
    ["diff"] = "keyword",
    ["set?"] = "keyword",
    ["list>set"] = "keyword",
    ["set>list"] = "keyword",
    ["integer?"] = "keyword",
    ["float?"] = "keyword",
    ["logical?"] = "keyword",
    ["char?"] = "keyword",
    ["string?"] = "keyword",
    ["list?"] = "keyword",
    ["ptr?"] = "keyword",
    ["file?"] = "keyword",
    ["null"] = "keyword",
    ["small"] = "keyword",
    ["stdin"] = "keyword",
    ["stdout"] = "keyword",
    ["stderr"] = "keyword",
    ["fopen"] = "keyword",
    ["fclose"] = "keyword",
    ["fflush"] = "keyword",
    ["feof"] = "keyword",
    ["fgetch"] = "keyword",
    ["fgets"] = "keyword",
    ["fread"] = "keyword",
    ["fputch"] = "keyword",
    ["fputchars"] = "keyword",
    ["fput"] = "keyword",
    ["fputln"] = "keyword",
    ["fseek"] = "keyword",
    ["ftell"] = "keyword",
    ["fremove"] = "keyword",
    ["frename"] = "keyword",
    ["include"] = "keyword",
    ["read-file"] = "keyword",
    ["write-file"] = "keyword",
    ["get"] = "keyword",
    ["i"] = "keyword",
    ["x"] = "keyword",
    ["dip"] = "keyword",
    ["dipd"] = "keyword",
    ["infra"] = "keyword",
    ["app1"] = "keyword",
    ["app2"] = "keyword",
    ["app3"] = "keyword",
    ["app4"] = "keyword",
    ["cleave"] = "keyword",
    ["nullary"] = "keyword",
    ["unary"] = "keyword",
    ["unary2"] = "keyword",
    ["unary3"] = "keyword",
    ["unary4"] = "keyword",
    ["binary"] = "keyword",
    ["ternary"] = "keyword",
    ["construct"] = "keyword",
    ["choice"] = "keyword",
    ["ifte"] = "keyword",
    ["branch"] = "keyword",
    ["cond"] = "keyword",
    ["case"] = "keyword",
    ["while"] = "keyword",
    ["times"] = "keyword",
    ["step"] = "keyword",
    ["each"] = "keyword",
    ["map"] = "keyword",
    ["filter"] = "keyword",
    ["fold"] = "keyword",
    ["all"] = "keyword",
    ["some"] = "keyword",
    ["split"] = "keyword",
    ["linrec"] = "keyword",
    ["binrec"] = "keyword",
    ["genrec"] = "keyword",
    ["ifinteger"] = "keyword",
    ["iffloat"] = "keyword",
    ["iflogical"] = "keyword",
    ["ifchar"] = "keyword",
    ["ifstring"] = "keyword",
    ["iflist"] = "keyword",
    ["ifset"] = "keyword",
    ["ifptr"] = "keyword",
    ["iffile"] = "keyword",
    ["put"] = "keyword",
    ["putln"] = "keyword",
    ["putchars"] = "keyword",
    ["nl"] = "keyword",
    ["words"] = "keyword",
    ["maxint"] = "keyword",
    ["setsize"] = "keyword",
    ["dlopen"] = "keyword",
    ["dlclose"] = "keyword",
    ["extern"] = "keyword",
    ["peek"] = "keyword",
    ["poke"] = "keyword",
    ["callback"] = "keyword",
    ["callback-free"] = "keyword",
    ["true"] = "keyword",
    ["false"] = "keyword",
    ["body"] = "keyword",
    ["defined?"] = "keyword",
    ["dictionary"] = "keyword",
    ["intern"] = "keyword",
    ["leaf"] = "keyword",
    ["name"] = "keyword",
    ["user"] = "keyword",
    ["primrec"] = "keyword",
    ["condlinrec"] = "keyword",
    ["treerec"] = "keyword",
    ["treefold"] = "keyword",
    ["treemap"] = "keyword",
    ["treestep"] = "keyword",
    ["treefilter"] = "keyword",
    ["treegenrec"] = "keyword",
    ["argc"] = "keyword",
    ["argv"] = "keyword",
    ["getenv"] = "keyword",
    ["system"] = "keyword",
    ["rand"] = "keyword",
    ["srand"] = "keyword",
    ["time"] = "keyword",
    ["clock"] = "keyword",
    ["frexp"] = "keyword",
    ["ldexp"] = "keyword",
  },
}
